#testing webhook
version: 0.0
os: linux
files:
  - source: .
    destination: /tmp
    overwrite: true
hooks:
  BeforeInstall:
    - location: script/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: script/install_dependencies01.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: script/start_server.sh
      timeout: 300
      runas: root


