name: CI/CD Pipeline
on:
  push:
    branches: [ master ]

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
     # Step 1
      - name: code checkout
        uses: actions/checkout@v2
      - name: AWS CodeDeploy
        uses: sourcetoad/aws-codedeploy-action@v1
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ap-south-1
          codedeploy_name: web_app
          codedeploy_group: web_app_deploymet_group
          s3_bucket: codedeploy
          s3_folder: artifacts
          codedeploy_register_only: true
          max_polling_iterations: 60
